version: '3'
services:

  mongogol:
    image: mongo
    restart: always
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    networks:
      - gol-network


  conway-api:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - mongogol
    networks:
      - gol-network

networks:
  gol-network: